#!/bin/bash

# Extract REMOTE_HOST like (x)inetd did. This requires to have a "%i" in
# the systemd service file as first argument.

REMOTE_HOST=$1
shift

REMOTE_HOST=${REMOTE_HOST##*-}
REMOTE_HOST=${REMOTE_HOST%:*}

export REMOTE_HOST
exec sgopherd "$@"
